services:
  parkourdevs-postgres:
    image: postgres
    restart: always
    volumes:
        - "parkourdevs-db:/var/lib/postgresql/data"
    ports:
        - "5434:5432"
    env_file:
      - .env

volumes:
  parkourdevs-db:
    external: true